{
 "title": "Space and Time Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(substrate_block_height,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "substrate_block_height{job=~\"$instance\", status=\"best\"}",
     "legendFormat": "Status - Best"
    },
    {
     "expr": "substrate_block_height{job=~\"$instance\", status=\"finalized\"}",
     "legendFormat": "Status - Finalized"
    },
    {
     "expr": "substrate_block_height{job=~\"$instance\", status=\"sync_target\"}",
     "legendFormat": "Status - Sync Target"
    }
   ]
  },
  {
   "title": "Block Verification Time (95th percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(substrate_block_verification_time_bucket{job=~\"$instance\"}[5m]))",
     "legendFormat": "Block Verification Time (95th percentile)"
    }
   ]
  },
  {
   "title": "Sync Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "substrate_block_height{job=~\"$instance\", status=\"sync_target\"} - ignoring (status) substrate_block_height{job=~\"$instance\", status=\"finalized\"}",
     "legendFormat": "Sync difference"
    }
   ]
  },
  {
   "title": "Import Time (95th percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(substrate_block_verification_and_import_time_bucket{job=~\"$instance\"}[5m]))",
     "legendFormat": "Import Time (95th percentile)"
    }
   ]
  },
  {
   "title": "Blocks Submitted Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(substrate_sync_import_queue_blocks_submitted{job=\"$instance\"}[5m])",
     "legendFormat": "Blocks Submitted Rate"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{job=\"$instance\"}",
     "legendFormat": "Pending Transactions"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"$instance\"}",
     "legendFormat": "Connected Peers"
    }
   ]
  }
 ]
}